[Week 9] Class4 3문제
What-is-algorithm/java-algorithm pull request #37
Opened 2024-01-17 11:36 UTC by eunbileeme

[2023.12.28 ~ 2023.12.31] 백준 Class4 백트래킹 관련 3문제입니다.
- 백준 Class4 2문제 및 Leetcode 1문제는 하루에 한 문제씩 순차적으로 올라갈 예정입니다.
- 이 점 양해부탁드립니다.

2024-01-18 06:20 UTC, JinDDung2 reviewed
같이 문제를 풀었기에 리뷰 생략..

2024-01-18 14:11 UTC, wanniDev requested changes
일단 나머지 문제를 또 공유해주신다면 마저 리뷰하도록 하겠습니다.

2024-01-18 14:11 UTC, wanniDev commented on src/silver/class4/NAndM4.java
> +                arr[depth] = i;
제 경우에는 조건에 맞는 모든 경우의 수열을 콜렉션에 담을려고 했는데, 오직 출력만을 수행하면 된다면 이런식으로 진행해도 되겠네요.

2024-01-24 15:42 UTC, yelimkin approved these changes

2024-01-24 15:42 UTC, yelimkin commented on src/silver/class4/NQueen.java
> +    // 1차원 배열로 풀었을 때는 i만 바뀌면 되지만, 2차원 배열로 풀었을 경우에는 i와 j가 모두 업데이트 되어야 할 것
정리하면서 문제를 푸는 방법 너무 좋은 것 같아요!

2024-01-28 02:18 UTC, wanniDev approved these changes
고생하셨습니다. :)

2024-01-31 03:49 UTC, JinDDung2 approved these changes
고생하셨습니다!

2024-02-02 16:34 UTC, merged